# Generated by Django 2.2.3 on 2019-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idid',
            field=models.CharField(default=10, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passpass',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
